name: Publish to npm

on:
  schedule:
    # run every 15 mins
    # publish script is idempodent and bails early if there's no work to be done
    # so we can safely run this on a regular interval to make sure our publish
    # is not too far behind foundry's
    - cron: "*/15 * * * *"
  workflow_dispatch:

# Ensure only one workflow/job is publishing to npm at a time
concurrency: publish

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: "https://registry.npmjs.org"
      - run: npm clean-install
      - run: npm run release:publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
